In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
#Import dataset

#df.head()

In [3]:
#Drop data attribute form the dataset

In [4]:
#Describe the dataset

In [5]:
#Show the correlation of the dataset

In [6]:
#Show the correlation in heatmap with anotations
#plt.title('Correlation between fearures')

In [8]:
# X = df.iloc[:, :-1].values
# y = df.iloc[:, -1].values

In [8]:
#Split the data into 70/30 (training / testing)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size, random_state = 0)

In [9]:
# Scale the data to be between -1 and 1
from sklearn.preprocessing import StandardScaler
#write the missing line here
X=scaler.fit_transform(X)
X

In [10]:
from sklearn.decomposition import PCA
#write the missing line here
pca.fit_transform(X)

In [11]:
#pca.get_covariance()

In [12]:
explained_variance=pca.explained_variance_ratio_
explained_variance

array([0.22759689, 0.19239519, 0.13044173, 0.1243596 , 0.10166382,
       0.08789696, 0.07756702, 0.03511623, 0.02296256])

In [13]:
pca=PCA(n_components=5)
X_new=pca.fit_transform(X)
X_new

array([[ 0.6687109 , -0.50509846, -0.10743874, -1.41283472, -0.53594688],
       [ 0.88840044, -0.60643616, -0.06260455, -1.48607316, -0.54043934],
       [ 0.7718913 , -0.55859516, -0.08014325, -1.46910439, -0.53923669],
       ...,
       [-0.63524079, -1.71533188,  1.11764542, -0.14244622, -0.19866317],
       [-0.80195686, -1.64566979,  1.091275  , -0.11369913, -0.19670135],
       [-0.66692408, -1.70731218,  1.11815057, -0.15632461, -0.19933369]])

In [14]:
pca.get_covariance()

array([[ 1.10001654,  0.46849868, -0.15468171, -0.16063907, -0.03764211,
         0.37170871,  0.18834917,  0.27603112, -0.07287558],
       [ 0.46849868,  0.99924673, -0.01317322, -0.00972662,  0.0172804 ,
         0.29669045, -0.01449876,  0.06663215, -0.06926927],
       [-0.15468171, -0.01317322,  1.14803264,  0.64475609, -0.0645176 ,
         0.02465262, -0.00755063, -0.02237854,  0.01920824],
       [-0.16063907, -0.00972662,  0.64475609,  1.14910051, -0.0391494 ,
         0.01452811, -0.01709238, -0.03637027,  0.01119622],
       [-0.03764211,  0.0172804 , -0.0645176 , -0.0391494 ,  0.99148801,
        -0.13214957, -0.02047991, -0.05407956, -0.09266313],
       [ 0.37170871,  0.29669045,  0.02465262,  0.01452811, -0.13214957,
         0.80384342,  0.09055438,  0.23472777,  0.08024244],
       [ 0.18834917, -0.01449876, -0.00755063, -0.01709238, -0.02047991,
         0.09055438,  0.91850576,  0.28315177, -0.19726346],
       [ 0.27603112,  0.06663215, -0.02237854, -0.03637027, -0

In [15]:
explained_variance=pca.explained_variance_ratio_
explained_variance

array([0.22759689, 0.19239519, 0.13044173, 0.1243596 , 0.10166382])

In [16]:
#train / test split (70/30)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size, random_state=1)
X_train.shape

(49747, 9)

In [17]:
# Establish model
from sklearn.ensemble import RandomForestRegressor
#Write missing line here

In [18]:
estimators = np.arange(10, 200, 10)
scores = []
for n in estimators:
    model.set_params(n_estimators=n)
    model.fit(X_train, y_train)
    scores.append(model.score(X_test, y_test))
print(scores) 

[0.9999946505622824, 0.999995511239143, 0.9999955784258836, 0.9999953247591565, 0.9999957282179863, 0.9999956073603192, 0.9999958118229926, 0.9999960555069142, 0.9999958099013698, 0.9999960867892076, 0.9999951078390412, 0.9999955469167736, 0.9999957807899207, 0.9999956815729936, 0.9999956245640483, 0.9999955662038431, 0.9999957539636102, 0.9999954514086148, 0.9999955336501195]


In [19]:
#plot a graph x-label = "n-estimator"
# y-label = "score"